### PR TITLE
docs: updated MainsailOS Setup Guide using rpi-imager

### PR DESCRIPTION
**Pull request by KwadFan**
Replaced Screenshots to newer Version.
Added Warning not to change Username.
Updated Screenshot of Update Section.
Refactored first boot for some styling.

Signed-off-by: Stephan Wendel <me@stephanwe.de>

### CODE REVIEW

**Comment by lixxbox** [comment]
PR still needs some extra work as discussed on Discord.

**Comment by lixxbox** [comment]
PR still needs some extra work as discussed on Discord.

**Review by prcutler — CHANGES_REQUESTED** [review]
Thanks for the PR!  This looks really good, I would just recommend some little things, mostly spelling:

In pi-imager:
Line 26: add the word file after zip: "(don't unpack the zip file;")
Line 35: popup should be pop-up
Line 49: replace "hit" with "click"
Line 57:  replace "click" with "clicking"

59: I would recommend: Please enable SSH!  Otherwise you will not be able to connect via SSH later.
64: Should be "preferred" with 2 r's
67: Did it change from mainsailos.local (which is what my install uses) to mainsail.local? (I don't know - do we want it the same as the default if it hasn't changed?)
75: "relays" should be "relies"
86: I would recommend a change to the sentence, making it: "The last step manages your..."

Let me know if you have any questions or need anything.

Paul

**Comment by KwadFan** [comment]
Please review latest changes. 

Line 26: add the word file after zip: "(don't unpack the zip file;")

This line doesnt exist anymore.

**Review by prcutler — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
